# Generated by Django 3.0.6 on 2020-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('certificate', models.FileField(upload_to='certificates')),
            ],
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_detail_id', models.IntegerField()),
                ('topic_no', models.CharField(max_length=15)),
                ('chapter_title', models.CharField(max_length=50)),
                ('chapter_ulr', models.TextField()),
                ('chapter_file', models.FileField(upload_to='course_file')),
            ],
        ),
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
                ('course_price', models.CharField(max_length=50)),
                ('course_image', models.ImageField(upload_to='course_image')),
            ],
        ),
        migrations.CreateModel(
            name='course_details_dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
                ('course_price', models.CharField(max_length=50)),
                ('course_image', models.ImageField(upload_to='course_image')),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_detail_id', models.IntegerField()),
                ('topic_title', models.CharField(max_length=50)),
                ('topic_part_count', models.CharField(max_length=15)),
            ],
        ),
    ]
