# Generated by Django 3.0.6 on 2020-05-28 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_tocken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tocken', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('conf_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='course_buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('buy_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_admin_ids', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('msg', models.TextField()),
                ('designation', models.CharField(max_length=10)),
                ('tocken_id', models.IntegerField()),
                ('msg_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('login_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_details_dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('login_id', models.IntegerField()),
            ],
        ),
    ]
